### ISSUE TITLE
Chef error when reconfiguring from AMI

### ISSUE THREAD

**Issue by radykal-com** [Graylog2/graylog2-cookbook#87]
Hello,

I have a tool that orchestrates the deploy of a single or multi-node graylog stack on Amazon Web Services with the provided OVA AMIs.

Randomly when doing the reconfigure command for first time in the master node it throws the following error.

````
2017-03-22 08:33:47,399 P7483 [INFO] 	[2017-03-22T08:33:44+01:00] INFO: template[/opt/graylog/sv/graylog-server/log/run] owner changed to 0
2017-03-22 08:33:47,399 P7483 [INFO] 	[2017-03-22T08:33:44+01:00] INFO: template[/opt/graylog/sv/graylog-server/log/run] group changed to 0
2017-03-22 08:33:47,399 P7483 [INFO] 	[2017-03-22T08:33:44+01:00] INFO: template[/opt/graylog/sv/graylog-server/log/run] mode changed to 755
2017-03-22 08:33:47,399 P7483 [INFO] 	[2017-03-22T08:33:44+01:00] INFO: template[/var/log/graylog/server/config] created file /var/log/graylog/server/config
2017-03-22 08:33:47,399 P7483 [INFO] 	[2017-03-22T08:33:44+01:00] INFO: template[/var/log/graylog/server/config] updated file contents /var/log/graylog/server/config
2017-03-22 08:33:47,399 P7483 [INFO] 	[2017-03-22T08:33:44+01:00] INFO: template[/var/log/graylog/server/config] owner changed to 0
2017-03-22 08:33:47,399 P7483 [INFO] 	[2017-03-22T08:33:44+01:00] INFO: template[/var/log/graylog/server/config] group changed to 0
2017-03-22 08:33:47,400 P7483 [INFO] 	[2017-03-22T08:33:44+01:00] INFO: link[/opt/graylog/init/graylog-server] created
2017-03-22 08:33:47,400 P7483 [INFO] 	[2017-03-22T08:33:44+01:00] INFO: link[/opt/graylog/service/graylog-server] created
2017-03-22 08:33:47,400 P7483 [INFO] 	[2017-03-22T08:33:45+01:00] INFO: ruby_block[supervise_graylog-server_sleep] called
2017-03-22 08:33:47,400 P7483 [INFO] 	[2017-03-22T08:33:45+01:00] INFO: execute[/opt/graylog/embedded/bin/graylog-ctl start graylog-server] ran successfully
2017-03-22 08:33:47,400 P7483 [INFO]
2017-03-22 08:33:47,400 P7483 [INFO] 	================================================================================
2017-03-22 08:33:47,400 P7483 [INFO] 	Error executing action `run` on resource 'ruby_block[add node to server list]'
2017-03-22 08:33:47,400 P7483 [INFO] 	================================================================================
2017-03-22 08:33:47,400 P7483 [INFO]
2017-03-22 08:33:47,400 P7483 [INFO] 	Errno::ECONNREFUSED
2017-03-22 08:33:47,400 P7483 [INFO] 	-------------------
2017-03-22 08:33:47,400 P7483 [INFO] 	Connection refused - connect(2) for "127.0.0.1" port 4001
2017-03-22 08:33:47,400 P7483 [INFO]
2017-03-22 08:33:47,400 P7483 [INFO] 	Cookbook Trace:
2017-03-22 08:33:47,400 P7483 [INFO] 	---------------
2017-03-22 08:33:47,400 P7483 [INFO] 	/opt/graylog/embedded/cookbooks/graylog/libraries/registry.rb:17:in `set_master'
2017-03-22 08:33:47,400 P7483 [INFO] 	/opt/graylog/embedded/cookbooks/graylog/recipes/graylog-server.rb:86:in `block (2 levels) in from_file'
2017-03-22 08:33:47,400 P7483 [INFO]
2017-03-22 08:33:47,400 P7483 [INFO] 	Resource Declaration:
2017-03-22 08:33:47,401 P7483 [INFO] 	---------------------
2017-03-22 08:33:47,401 P7483 [INFO] 	# In /opt/graylog/embedded/cookbooks/graylog/recipes/graylog-server.rb
2017-03-22 08:33:47,401 P7483 [INFO]
2017-03-22 08:33:47,401 P7483 [INFO] 	 84: ruby_block "add node to server list" do
2017-03-22 08:33:47,401 P7483 [INFO] 	 85:   block do
2017-03-22 08:33:47,401 P7483 [INFO] 	 86:     $registry.set_master
2017-03-22 08:33:47,401 P7483 [INFO] 	 87:     $registry.add_gl_server(node['ipaddress'])
2017-03-22 08:33:47,401 P7483 [INFO] 	 88:     $registry.add_es_node(node['ipaddress'])
2017-03-22 08:33:47,401 P7483 [INFO] 	 89:   end
2017-03-22 08:33:47,401 P7483 [INFO] 	 90: end
2017-03-22 08:33:47,401 P7483 [INFO]
2017-03-22 08:33:47,401 P7483 [INFO] 	Compiled Resource:
2017-03-22 08:33:47,401 P7483 [INFO] 	------------------
2017-03-22 08:33:47,401 P7483 [INFO] 	# Declared in /opt/graylog/embedded/cookbooks/graylog/recipes/graylog-server.rb:84:in `from_file'
2017-03-22 08:33:47,401 P7483 [INFO]
2017-03-22 08:33:47,401 P7483 [INFO] 	ruby_block("add node to server list") do
2017-03-22 08:33:47,401 P7483 [INFO] 	  action [:run]
2017-03-22 08:33:47,401 P7483 [INFO] 	  retries 0
2017-03-22 08:33:47,401 P7483 [INFO] 	  retry_delay 2
2017-03-22 08:33:47,402 P7483 [INFO] 	  default_guard_interpreter :default
2017-03-22 08:33:47,402 P7483 [INFO] 	  block_name "add node to server list"
2017-03-22 08:33:47,402 P7483 [INFO] 	  declared_type :ruby_block
2017-03-22 08:33:47,402 P7483 [INFO] 	  cookbook_name :graylog
2017-03-22 08:33:47,402 P7483 [INFO] 	  recipe_name "graylog-server"
2017-03-22 08:33:47,402 P7483 [INFO] 	  block #<Proc:0x00000004dfaf08@/opt/graylog/embedded/cookbooks/graylog/recipes/graylog-server.rb:85>
2017-03-22 08:33:47,402 P7483 [INFO] 	end
2017-03-22 08:33:47,402 P7483 [INFO]
````

What I've found so far is that sometimes ETCD is not yet ready when Chef executes the 'add node to server list'. Seems both commands are executed one after the other, so if for any reason etcd delays the start, the command will fail.

With the same code, the reconfigure will fail about 2-3 times out of 10.
Would be nice if there is any way to ensure etcd is up and listening on port 4001 before trying to run the consecutive actions.

I tried to find where it's this code across some graylog projects but had no luck.

If someone can point me what project has the code I could try to code a fix.

Thanks you,

**Comment by radykal-com** [comment]
Hello,

Just found the source code for this. Its in the omnibus repo, so closing this and opening the issue there.
