### ISSUE TITLE
authbind Parent directory /etc/authbind/byport does not exist.

### ISSUE THREAD

**Issue by runningman84** [Graylog2/graylog2-cookbook#9]
This happens on a new Ubuntu 14.04 box:
```
Recipe: graylog2::default
  * remote_file[/var/chef/cache/graylog2-0.92-repository-ubuntu14.04_latest.deb] action create_if_missing (up to date)
  * execute[apt-update] action nothing (skipped due to action :nothing)
  * apt_package[graylog2-0.92-repository-ubuntu14.04_latest.deb] action install (up to date)
Recipe: graylog2::server
  * apt_package[graylog2-server] action install (up to date)
  * directory[/var/run/graylog2] action create (up to date)
  * service[graylog2-server] action nothing (skipped due to action :nothing)
  * template[/etc/graylog2.conf] action create (up to date)
  * template[/etc/default/graylog2-server] action create[2015-01-15T15:11:39+00:00] INFO: template[/etc/default/graylog2-server] backed up to /var/chef/backup/etc/default/graylog2-server.chef-20150115151139.019786
[2015-01-15T15:11:39+00:00] INFO: template[/etc/default/graylog2-server] updated file contents /etc/default/graylog2-server

    - update content in file /etc/default/graylog2-server from c13a92 to 56a42c
    --- /etc/default/graylog2-server	2015-01-15 14:00:52.010540644 +0000
    +++ /tmp/chef-rendered-template20150115-12545-1hcjjjg	2015-01-15 15:11:39.014540644 +0000
    @@ -6,5 +6,5 @@
     
     # Program that will be used to wrap the graylog2-server command. Useful to
     # support programs like authbind.
    -GRAYLOG2_COMMAND_WRAPPER=""
    +GRAYLOG2_COMMAND_WRAPPER="authbind"
  * template[/etc/graylog2/server/log4j.xml] action create (up to date)
  * template[/etc/graylog2-elasticsearch.yml] action create (up to date)
Recipe: graylog2::web
  * apt_package[graylog2-web] action install (up to date)
  * service[graylog2-web] action nothing (skipped due to action :nothing)
  * template[/etc/graylog2/web/graylog2-web-interface.conf] action create (up to date)
  * template[/etc/default/graylog2-web] action create (up to date)
  * template[/etc/graylog2/web/logback.xml] action create (up to date)
Recipe: graylog2::authbind
  * authbind_port[AuthBind Graylog2 port 514] action add
    * file[/etc/authbind/byport/!514] action create
      * Parent directory /etc/authbind/byport does not exist.
      ================================================================================
      Error executing action `create` on resource 'file[/etc/authbind/byport/!514]'
      ================================================================================
      
      Chef::Exceptions::EnclosingDirectoryDoesNotExist
      ------------------------------------------------
      Parent directory /etc/authbind/byport does not exist.
      
      Resource Declaration:
      ---------------------
      # In /var/chef/cache/cookbooks/authbind/providers/port.rb
      
       23:   file "/etc/authbind/byport/#{port}" do
       24:     owner new_resource.user
       25:     group new_resource.group if new_resource.group
       26:     mode "0550"
       27:     action :create
       28:   end
       29: end
      
      Compiled Resource:
      ------------------
      # Declared in /var/chef/cache/cookbooks/authbind/providers/port.rb:23:in `block in class_from_file'
      
      file("/etc/authbind/byport/!514") do
        action [:create]
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        path "/etc/authbind/byport/!514"
        backup 5
        atomic_update true
        declared_type :file
        cookbook_name "graylog2"
        owner "graylog2"
        mode "0550"
      end
      
[2015-01-15T15:11:39+00:00] INFO: Running queued delayed notifications before re-raising exception
    
    ================================================================================
    Error executing action `add` on resource 'authbind_port[AuthBind Graylog2 port 514]'
    ================================================================================
    
    Chef::Exceptions::EnclosingDirectoryDoesNotExist
    ------------------------------------------------
    file[/etc/authbind/byport/!514] (/var/chef/cache/cookbooks/authbind/providers/port.rb line 23) had an error: Chef::Exceptions::EnclosingDirectoryDoesNotExist: Parent directory /etc/authbind/byport does not exist.
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/graylog2/recipes/authbind.rb
    
     12:     authbind_port "AuthBind Graylog2 port #{node.graylog2[:authorized_ports]}" do
     13:         port node.graylog2[:authorized_ports]
     14:         user node.graylog2[:user]
     15:     end
     16:   end
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/graylog2/recipes/authbind.rb:12:in `from_file'
    
    authbind_port("AuthBind Graylog2 port 514") do
      action :add
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :authbind_port
      cookbook_name "graylog2"
      recipe_name "authbind"
      port 514
      user "graylog2"
    end
    
[2015-01-15T15:11:39+00:00] INFO: Running queued delayed notifications before re-raising exception
[2015-01-15T15:11:39+00:00] INFO: template[/etc/default/graylog2-server] sending restart action to service[graylog2-server] (delayed)
Recipe: graylog2::server
  * service[graylog2-server] action restart[2015-01-15T15:11:43+00:00] INFO: service[graylog2-server] restarted

    - restart service service[graylog2-server]

Running handlers:
[2015-01-15T15:11:43+00:00] ERROR: Running exception handlers
Running handlers complete
[2015-01-15T15:11:43+00:00] ERROR: Exception handlers complete
[2015-01-15T15:11:43+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 8 resources updated in 27.321896223 seconds
```

**Comment by mariussturm** [comment]
Thanks for the report!
The documentation was not clear that you have to include the `authbind` cookbook in order to make use of the recipe: https://supermarket.chef.io/cookbooks/authbind
I added a sentence in the README and also make an explicit include in graylog2::authbind now to fail if the cookbook is not there.

**Comment by runningman84** [comment]
you could just include the authbind cookbook in graylog2::authbind recipe?

**Comment by mariussturm** [comment]
Yes, I did exactly that: https://github.com/Graylog2/graylog2-cookbook/blob/master/recipes/authbind.rb#L1
